//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.30 at 03:11:16 PM CEST 
//


package com.telefonica.schemas.unica.rest.mms.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReceivedMessagesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReceivedMessagesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="receivedMessages" type="{http://www.telefonica.com/schemas/UNICA/REST/mms/v1/}MessageReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReceivedMessagesType", propOrder = {
    "receivedMessages"
})
public class ReceivedMessagesType {

    protected List<MessageReferenceType> receivedMessages;

    /**
     * Gets the value of the receivedMessages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the receivedMessages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReceivedMessages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageReferenceType }
     * 
     * 
     */
    public List<MessageReferenceType> getReceivedMessages() {
        if (receivedMessages == null) {
            receivedMessages = new ArrayList<MessageReferenceType>();
        }
        return this.receivedMessages;
    }

    /**
     * Sets the value of the receivedMessages property.
     * 
     * @param receivedMessages
     *     allowed object is
     *     {@link MessageReferenceType }
     *     
     */
    public void setReceivedMessages(List<MessageReferenceType> receivedMessages) {
        this.receivedMessages = receivedMessages;
    }

}
