//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 09:34:35 AM CEST 
//


package com.telefonica.schemas.unica.rest.directory.v1._2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.telefonica.schemas.unica.rest.common.v1.FlagType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.telefonica.schemas.unica.rest.directory.v1._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Icc_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/2", "icc");
    private final static QName _MmsVideo_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/2", "mmsVideo");
    private final static QName _RestMens_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/2", "restMens");
    private final static QName _VideoStreaming_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/2", "videoStreaming");
    private final static QName _WapPush_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/2", "wapPush");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.telefonica.schemas.unica.rest.directory.v1._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/2", name = "icc")
    public JAXBElement<String> createIcc(String value) {
        return new JAXBElement<String>(_Icc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/2", name = "mmsVideo")
    public JAXBElement<FlagType> createMmsVideo(FlagType value) {
        return new JAXBElement<FlagType>(_MmsVideo_QNAME, FlagType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/2", name = "restMens")
    public JAXBElement<String> createRestMens(String value) {
        return new JAXBElement<String>(_RestMens_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/2", name = "videoStreaming")
    public JAXBElement<FlagType> createVideoStreaming(FlagType value) {
        return new JAXBElement<FlagType>(_VideoStreaming_QNAME, FlagType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/2", name = "wapPush")
    public JAXBElement<FlagType> createWapPush(FlagType value) {
        return new JAXBElement<FlagType>(_WapPush_QNAME, FlagType.class, null, value);
    }

}
