//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.30 at 03:11:16 PM CEST 
//


package com.telefonica.schemas.unica.rpc.payment.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * extends RPC Definition MethodResponseType
 * 
 * <p>Java class for MethodResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MethodResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.telefonica.com/schemas/UNICA/RPC/definition/v1}MethodResponseType">
 *       &lt;sequence>
 *         &lt;element name="result" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="paymentResult" type="{http://www.telefonica.com/schemas/UNICA/RPC/payment/v1}PaymentResultType"/>
 *                   &lt;element name="getPaymentStatusResult" type="{http://www.telefonica.com/schemas/UNICA/RPC/payment/v1}GetPaymentStatusResultType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MethodResponseType", propOrder = {
    "result"
})
public class MethodResponseType
    extends com.telefonica.schemas.unica.rpc.definition.v1.MethodResponseType
{

    protected MethodResponseType.Result result;

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link MethodResponseType.Result }
     *     
     */
    public MethodResponseType.Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodResponseType.Result }
     *     
     */
    public void setResult(MethodResponseType.Result value) {
        this.result = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="paymentResult" type="{http://www.telefonica.com/schemas/UNICA/RPC/payment/v1}PaymentResultType"/>
     *         &lt;element name="getPaymentStatusResult" type="{http://www.telefonica.com/schemas/UNICA/RPC/payment/v1}GetPaymentStatusResultType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paymentResult",
        "getPaymentStatusResult"
    })
    public static class Result {

        protected PaymentResultType paymentResult;
        protected GetPaymentStatusResultType getPaymentStatusResult;

        /**
         * Gets the value of the paymentResult property.
         * 
         * @return
         *     possible object is
         *     {@link PaymentResultType }
         *     
         */
        public PaymentResultType getPaymentResult() {
            return paymentResult;
        }

        /**
         * Sets the value of the paymentResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link PaymentResultType }
         *     
         */
        public void setPaymentResult(PaymentResultType value) {
            this.paymentResult = value;
        }

        /**
         * Gets the value of the getPaymentStatusResult property.
         * 
         * @return
         *     possible object is
         *     {@link GetPaymentStatusResultType }
         *     
         */
        public GetPaymentStatusResultType getGetPaymentStatusResult() {
            return getPaymentStatusResult;
        }

        /**
         * Sets the value of the getPaymentStatusResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link GetPaymentStatusResultType }
         *     
         */
        public void setGetPaymentStatusResult(GetPaymentStatusResultType value) {
            this.getPaymentStatusResult = value;
        }

    }

}
