//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.30 at 03:11:16 PM CEST 
//


package com.telefonica.schemas.unica.rpc.common.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Group of elements, only ONE of the child elements may be given for a UserId
 * 
 * <p>Java class for UserIdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserIdType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="phoneNumber" type="{http://www.telefonica.com/schemas/UNICA/RPC/common/v1}E164Type"/>
 *         &lt;element name="anyUri" type="{http://www.telefonica.com/schemas/UNICA/RPC/common/v1}AnyURIType"/>
 *         &lt;element name="ipAddress" type="{http://www.telefonica.com/schemas/UNICA/RPC/common/v1}IpAddressType"/>
 *         &lt;element name="alias" type="{http://www.telefonica.com/schemas/UNICA/RPC/common/v1}AliasType"/>
 *         &lt;element name="otherId" type="{http://www.telefonica.com/schemas/UNICA/RPC/common/v1}OtherIdType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserIdType", propOrder = {
    "phoneNumber",
    "anyUri",
    "ipAddress",
    "alias",
    "otherId"
})
public class UserIdType {

    protected String phoneNumber;
    protected String anyUri;
    protected IpAddressType ipAddress;
    protected String alias;
    protected OtherIdType otherId;

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the anyUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnyUri() {
        return anyUri;
    }

    /**
     * Sets the value of the anyUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnyUri(String value) {
        this.anyUri = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link IpAddressType }
     *     
     */
    public IpAddressType getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpAddressType }
     *     
     */
    public void setIpAddress(IpAddressType value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the otherId property.
     * 
     * @return
     *     possible object is
     *     {@link OtherIdType }
     *     
     */
    public OtherIdType getOtherId() {
        return otherId;
    }

    /**
     * Sets the value of the otherId property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherIdType }
     *     
     */
    public void setOtherId(OtherIdType value) {
        this.otherId = value;
    }

}
