//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.30 at 03:11:16 PM CEST 
//


package com.telefonica.schemas.unica.rest.location.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.telefonica.schemas.unica.rest.location.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TerminalLocation_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/location/v1/", "terminalLocation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.telefonica.schemas.unica.rest.location.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LocationDataType }
     * 
     */
    public LocationDataType createLocationDataType() {
        return new LocationDataType();
    }

    /**
     * Create an instance of {@link LocationInfoType }
     * 
     */
    public LocationInfoType createLocationInfoType() {
        return new LocationInfoType();
    }

    /**
     * Create an instance of {@link CoordinatesType }
     * 
     */
    public CoordinatesType createCoordinatesType() {
        return new CoordinatesType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/location/v1/", name = "terminalLocation")
    public JAXBElement<LocationDataType> createTerminalLocation(LocationDataType value) {
        return new JAXBElement<LocationDataType>(_TerminalLocation_QNAME, LocationDataType.class, null, value);
    }

}
