//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.08 at 02:31:37 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.telefonica.com/schemas/UNICA/REST/sgap/v1/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.telefonica.schemas.unica.rest.sgap.v1;
