//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.30 at 03:11:16 PM CEST 
//


package com.telefonica.schemas.unica.rest.sgap.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="creative_element" type="{http://www.telefonica.com/schemas/UNICA/REST/sgap/v1/}CreativeElementType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ad_presentation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceType", propOrder = {
    "creativeElement"
})
public class ResourceType {

    @XmlElement(name = "creative_element", required = true)
    protected List<CreativeElementType> creativeElement;
    @XmlAttribute(name = "ad_presentation", required = true)
    protected String adPresentation;

    /**
     * Gets the value of the creativeElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creativeElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreativeElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreativeElementType }
     * 
     * 
     */
    public List<CreativeElementType> getCreativeElement() {
        if (creativeElement == null) {
            creativeElement = new ArrayList<CreativeElementType>();
        }
        return this.creativeElement;
    }

    /**
     * Gets the value of the adPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdPresentation() {
        return adPresentation;
    }

    /**
     * Sets the value of the adPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdPresentation(String value) {
        this.adPresentation = value;
    }

    /**
     * Sets the value of the creativeElement property.
     * 
     * @param creativeElement
     *     allowed object is
     *     {@link CreativeElementType }
     *     
     */
    public void setCreativeElement(List<CreativeElementType> creativeElement) {
        this.creativeElement = creativeElement;
    }

}
