//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.30 at 03:11:16 PM CEST 
//


package com.telefonica.schemas.unica.rest.sgap.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimpleAdRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleAdRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ad_request_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ad_presentation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ad_space" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="user_agent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="keywords" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="protecion_policy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="target_user_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleAdRequestType", propOrder = {
    "adRequestId",
    "adPresentation",
    "adSpace",
    "userAgent",
    "keywords",
    "protecionPolicy",
    "country",
    "targetUserId"
})
public class SimpleAdRequestType {

    @XmlElement(name = "ad_request_id", required = true)
    protected String adRequestId;
    @XmlElement(name = "ad_presentation")
    protected String adPresentation;
    @XmlElement(name = "ad_space", required = true)
    protected String adSpace;
    @XmlElement(name = "user_agent", required = true)
    protected String userAgent;
    protected String keywords;
    @XmlElement(name = "protecion_policy")
    protected String protecionPolicy;
    protected String country;
    @XmlElement(name = "target_user_id")
    protected String targetUserId;

    /**
     * Gets the value of the adRequestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdRequestId() {
        return adRequestId;
    }

    /**
     * Sets the value of the adRequestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdRequestId(String value) {
        this.adRequestId = value;
    }

    /**
     * Gets the value of the adPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdPresentation() {
        return adPresentation;
    }

    /**
     * Sets the value of the adPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdPresentation(String value) {
        this.adPresentation = value;
    }

    /**
     * Gets the value of the adSpace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdSpace() {
        return adSpace;
    }

    /**
     * Sets the value of the adSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdSpace(String value) {
        this.adSpace = value;
    }

    /**
     * Gets the value of the userAgent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * Sets the value of the userAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserAgent(String value) {
        this.userAgent = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeywords(String value) {
        this.keywords = value;
    }

    /**
     * Gets the value of the protecionPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtecionPolicy() {
        return protecionPolicy;
    }

    /**
     * Sets the value of the protecionPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtecionPolicy(String value) {
        this.protecionPolicy = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the targetUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetUserId() {
        return targetUserId;
    }

    /**
     * Sets the value of the targetUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetUserId(String value) {
        this.targetUserId = value;
    }

}
