//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.21 at 04:22:57 PM CET 
//


package com.telefonica.schemas.unica.rpc.trusted_payment.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * extends RPC Definition  MethodCallType
 * 
 * <p>Java class for MethodCallType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MethodCallType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.telefonica.com/schemas/UNICA/RPC/definition/v1}MethodCallType">
 *       &lt;sequence>
 *         &lt;element name="method" type="{http://www.telefonica.com/schemas/UNICA/RPC/trusted_payment/v1}MethodType"/>
 *         &lt;element name="params" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="paymentParams" type="{http://www.telefonica.com/schemas/UNICA/RPC/trusted_payment/v1}PaymentParamsType"/>
 *                   &lt;element name="refundParams" type="{http://www.telefonica.com/schemas/UNICA/RPC/trusted_payment/v1}RefundParamsType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MethodCallType", propOrder = {
    "method",
    "params"
})
public class MethodCallType
    extends com.telefonica.schemas.unica.rpc.definition.v1.MethodCallType
{

    @XmlElement(required = true)
    protected MethodType method;
    protected MethodCallType.Params params;

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link MethodType }
     *     
     */
    public MethodType getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodType }
     *     
     */
    public void setMethod(MethodType value) {
        this.method = value;
    }

    /**
     * Gets the value of the params property.
     * 
     * @return
     *     possible object is
     *     {@link MethodCallType.Params }
     *     
     */
    public MethodCallType.Params getParams() {
        return params;
    }

    /**
     * Sets the value of the params property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodCallType.Params }
     *     
     */
    public void setParams(MethodCallType.Params value) {
        this.params = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="paymentParams" type="{http://www.telefonica.com/schemas/UNICA/RPC/trusted_payment/v1}PaymentParamsType"/>
     *         &lt;element name="refundParams" type="{http://www.telefonica.com/schemas/UNICA/RPC/trusted_payment/v1}RefundParamsType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paymentParams",
        "refundParams"
    })
    public static class Params {

        protected PaymentParamsType paymentParams;
        protected RefundParamsType refundParams;

        /**
         * Gets the value of the paymentParams property.
         * 
         * @return
         *     possible object is
         *     {@link PaymentParamsType }
         *     
         */
        public PaymentParamsType getPaymentParams() {
            return paymentParams;
        }

        /**
         * Sets the value of the paymentParams property.
         * 
         * @param value
         *     allowed object is
         *     {@link PaymentParamsType }
         *     
         */
        public void setPaymentParams(PaymentParamsType value) {
            this.paymentParams = value;
        }

        /**
         * Gets the value of the refundParams property.
         * 
         * @return
         *     possible object is
         *     {@link RefundParamsType }
         *     
         */
        public RefundParamsType getRefundParams() {
            return refundParams;
        }

        /**
         * Sets the value of the refundParams property.
         * 
         * @param value
         *     allowed object is
         *     {@link RefundParamsType }
         *     
         */
        public void setRefundParams(RefundParamsType value) {
            this.refundParams = value;
        }

    }

}
