//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.30 at 03:11:16 PM CEST 
//


package com.telefonica.schemas.unica.rest.directory.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import com.telefonica.schemas.unica.rest.common.v1.AddressType;
import com.telefonica.schemas.unica.rest.common.v1.FlagType;
import com.telefonica.schemas.unica.rest.common.v1.GenderType;
import com.telefonica.schemas.unica.rest.common.v1.IpAddressType;
import com.telefonica.schemas.unica.rest.common.v1.OtherIdType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.telefonica.schemas.unica.rest.directory.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UserInfoTypeUserAccessInfo_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "userAccessInfo");
    private final static QName _UserInfoTypeUserTerminalInfo_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "userTerminalInfo");
    private final static QName _UserInfoTypeUserProfile_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "userProfile");
    private final static QName _UserInfoTypeUserPersonalInfo_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "userPersonalInfo");
    private final static QName _UserInfoTypeUserIdentities_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "userIdentities");
    private final static QName _UserInfo_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "userInfo");
    private final static QName _UserAccessInfoTypeRoaming_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "roaming");
    private final static QName _UserAccessInfoTypeApn_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "apn");
    private final static QName _UserAccessInfoTypeAccessType_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "accessType");
    private final static QName _UserAccessInfoTypeIpAddress_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "ipAddress");
    private final static QName _UserAccessInfoTypeConnectionTime_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "connectionTime");
    private final static QName _UserAccessInfoTypeConnected_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "connected");
    private final static QName _UserIdentitiesTypeSipUri_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "sipUri");
    private final static QName _UserIdentitiesTypeOtherId_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "otherId");
    private final static QName _UserIdentitiesTypePhoneNumber_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "phoneNumber");
    private final static QName _UserIdentitiesTypeAlias_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "alias");
    private final static QName _UserIdentitiesTypeEmail_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "email");
    private final static QName _UserIdentitiesTypeTelUri_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "telUri");
    private final static QName _UserPersonalInfoTypeNamePrefix_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "namePrefix");
    private final static QName _UserPersonalInfoTypeDisplayName_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "displayName");
    private final static QName _UserPersonalInfoTypeLastUpdated_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "lastUpdated");
    private final static QName _UserPersonalInfoTypeGender_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "gender");
    private final static QName _UserPersonalInfoTypeAddress_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "address");
    private final static QName _UserPersonalInfoTypeNameSufix_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "nameSufix");
    private final static QName _UserPersonalInfoTypeName_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "name");
    private final static QName _UserPersonalInfoTypeBirthday_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "birthday");
    private final static QName _UserProfileTypeParentalControl_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "parentalControl");
    private final static QName _UserProfileTypeUserType_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "userType");
    private final static QName _UserProfileTypeDiversionMsisdn_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "diversionMsisdn");
    private final static QName _UserProfileTypeOperatorId_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "operatorId");
    private final static QName _UserProfileTypeSegment_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "segment");
    private final static QName _UserProfileTypeEnterpriseName_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "enterpriseName");
    private final static QName _UserProfileTypeRestMens_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "restMens");
    private final static QName _UserProfileTypeMmsStatus_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "mmsStatus");
    private final static QName _UserProfileTypeOcb_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "ocb");
    private final static QName _UserProfileTypeSubsegment_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "subsegment");
    private final static QName _UserProfileTypeImsi_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "imsi");
    private final static QName _UserProfileTypeLanguage_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "language");
    private final static QName _UserProfileTypeIcc_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "icc");
    private final static QName _UserProfileTypeIcb_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "icb");
    private final static QName _UserProfileTypeSimType_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "simType");
    private final static QName _UserProfileTypeCreditControl_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "creditControl");
    private final static QName _UserTerminalInfoTypeScreenResolution_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "screenResolution");
    private final static QName _UserTerminalInfoTypeVersion_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "version");
    private final static QName _UserTerminalInfoTypeEms_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "ems");
    private final static QName _UserTerminalInfoTypeEmsMaxNumber_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "emsMaxNumber");
    private final static QName _UserTerminalInfoTypeMms_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "mms");
    private final static QName _UserTerminalInfoTypeAdcOTA_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "adc_OTA");
    private final static QName _UserTerminalInfoTypeSyncMlVersion_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "syncMlVersion");
    private final static QName _UserTerminalInfoTypeWapPush_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "wapPush");
    private final static QName _UserTerminalInfoTypeStatus_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "status");
    private final static QName _UserTerminalInfoTypeImei_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "imei");
    private final static QName _UserTerminalInfoTypeWap_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "wap");
    private final static QName _UserTerminalInfoTypeEmn_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "emn");
    private final static QName _UserTerminalInfoTypeModel_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "model");
    private final static QName _UserTerminalInfoTypeSmartMessaging_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "smartMessaging");
    private final static QName _UserTerminalInfoTypeMmsVideo_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "mmsVideo");
    private final static QName _UserTerminalInfoTypeBrand_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "brand");
    private final static QName _UserTerminalInfoTypeVideoStreaming_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "videoStreaming");
    private final static QName _UserTerminalInfoTypeSyncMl_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "syncMl");
    private final static QName _UserTerminalInfoTypeUssdPhase_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", "ussdPhase");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.telefonica.schemas.unica.rest.directory.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserTerminalInfoType }
     * 
     */
    public UserTerminalInfoType createUserTerminalInfoType() {
        return new UserTerminalInfoType();
    }

    /**
     * Create an instance of {@link UserProfileType }
     * 
     */
    public UserProfileType createUserProfileType() {
        return new UserProfileType();
    }

    /**
     * Create an instance of {@link UserPersonalInfoType }
     * 
     */
    public UserPersonalInfoType createUserPersonalInfoType() {
        return new UserPersonalInfoType();
    }

    /**
     * Create an instance of {@link UserIdentitiesType }
     * 
     */
    public UserIdentitiesType createUserIdentitiesType() {
        return new UserIdentitiesType();
    }

    /**
     * Create an instance of {@link UserAccessInfoType }
     * 
     */
    public UserAccessInfoType createUserAccessInfoType() {
        return new UserAccessInfoType();
    }

    /**
     * Create an instance of {@link UserInfoType }
     * 
     */
    public UserInfoType createUserInfoType() {
        return new UserInfoType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link SubscribedServiceType }
     * 
     */
    public SubscribedServiceType createSubscribedServiceType() {
        return new SubscribedServiceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserAccessInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "userAccessInfo", scope = UserInfoType.class)
    public JAXBElement<UserAccessInfoType> createUserInfoTypeUserAccessInfo(UserAccessInfoType value) {
        return new JAXBElement<UserAccessInfoType>(_UserInfoTypeUserAccessInfo_QNAME, UserAccessInfoType.class, UserInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserTerminalInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "userTerminalInfo", scope = UserInfoType.class)
    public JAXBElement<UserTerminalInfoType> createUserInfoTypeUserTerminalInfo(UserTerminalInfoType value) {
        return new JAXBElement<UserTerminalInfoType>(_UserInfoTypeUserTerminalInfo_QNAME, UserTerminalInfoType.class, UserInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserProfileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "userProfile", scope = UserInfoType.class)
    public JAXBElement<UserProfileType> createUserInfoTypeUserProfile(UserProfileType value) {
        return new JAXBElement<UserProfileType>(_UserInfoTypeUserProfile_QNAME, UserProfileType.class, UserInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserPersonalInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "userPersonalInfo", scope = UserInfoType.class)
    public JAXBElement<UserPersonalInfoType> createUserInfoTypeUserPersonalInfo(UserPersonalInfoType value) {
        return new JAXBElement<UserPersonalInfoType>(_UserInfoTypeUserPersonalInfo_QNAME, UserPersonalInfoType.class, UserInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserIdentitiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "userIdentities", scope = UserInfoType.class)
    public JAXBElement<UserIdentitiesType> createUserInfoTypeUserIdentities(UserIdentitiesType value) {
        return new JAXBElement<UserIdentitiesType>(_UserInfoTypeUserIdentities_QNAME, UserIdentitiesType.class, UserInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "userInfo")
    public JAXBElement<UserInfoType> createUserInfo(UserInfoType value) {
        return new JAXBElement<UserInfoType>(_UserInfo_QNAME, UserInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserAccessInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "userAccessInfo")
    public JAXBElement<UserAccessInfoType> createUserAccessInfo(UserAccessInfoType value) {
        return new JAXBElement<UserAccessInfoType>(_UserInfoTypeUserAccessInfo_QNAME, UserAccessInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserIdentitiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "userIdentities")
    public JAXBElement<UserIdentitiesType> createUserIdentities(UserIdentitiesType value) {
        return new JAXBElement<UserIdentitiesType>(_UserInfoTypeUserIdentities_QNAME, UserIdentitiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserProfileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "userProfile")
    public JAXBElement<UserProfileType> createUserProfile(UserProfileType value) {
        return new JAXBElement<UserProfileType>(_UserInfoTypeUserProfile_QNAME, UserProfileType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserTerminalInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "userTerminalInfo")
    public JAXBElement<UserTerminalInfoType> createUserTerminalInfo(UserTerminalInfoType value) {
        return new JAXBElement<UserTerminalInfoType>(_UserInfoTypeUserTerminalInfo_QNAME, UserTerminalInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserPersonalInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "userPersonalInfo")
    public JAXBElement<UserPersonalInfoType> createUserPersonalInfo(UserPersonalInfoType value) {
        return new JAXBElement<UserPersonalInfoType>(_UserInfoTypeUserPersonalInfo_QNAME, UserPersonalInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "roaming", scope = UserAccessInfoType.class)
    public JAXBElement<FlagType> createUserAccessInfoTypeRoaming(FlagType value) {
        return new JAXBElement<FlagType>(_UserAccessInfoTypeRoaming_QNAME, FlagType.class, UserAccessInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "apn", scope = UserAccessInfoType.class)
    public JAXBElement<String> createUserAccessInfoTypeApn(String value) {
        return new JAXBElement<String>(_UserAccessInfoTypeApn_QNAME, String.class, UserAccessInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "accessType", scope = UserAccessInfoType.class)
    public JAXBElement<String> createUserAccessInfoTypeAccessType(String value) {
        return new JAXBElement<String>(_UserAccessInfoTypeAccessType_QNAME, String.class, UserAccessInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IpAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "ipAddress", scope = UserAccessInfoType.class)
    public JAXBElement<IpAddressType> createUserAccessInfoTypeIpAddress(IpAddressType value) {
        return new JAXBElement<IpAddressType>(_UserAccessInfoTypeIpAddress_QNAME, IpAddressType.class, UserAccessInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "connectionTime", scope = UserAccessInfoType.class)
    public JAXBElement<Long> createUserAccessInfoTypeConnectionTime(Long value) {
        return new JAXBElement<Long>(_UserAccessInfoTypeConnectionTime_QNAME, Long.class, UserAccessInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "connected", scope = UserAccessInfoType.class)
    public JAXBElement<FlagType> createUserAccessInfoTypeConnected(FlagType value) {
        return new JAXBElement<FlagType>(_UserAccessInfoTypeConnected_QNAME, FlagType.class, UserAccessInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IpAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "ipAddress", scope = UserIdentitiesType.class)
    public JAXBElement<IpAddressType> createUserIdentitiesTypeIpAddress(IpAddressType value) {
        return new JAXBElement<IpAddressType>(_UserAccessInfoTypeIpAddress_QNAME, IpAddressType.class, UserIdentitiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "sipUri", scope = UserIdentitiesType.class)
    public JAXBElement<String> createUserIdentitiesTypeSipUri(String value) {
        return new JAXBElement<String>(_UserIdentitiesTypeSipUri_QNAME, String.class, UserIdentitiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherIdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "otherId", scope = UserIdentitiesType.class)
    public JAXBElement<OtherIdType> createUserIdentitiesTypeOtherId(OtherIdType value) {
        return new JAXBElement<OtherIdType>(_UserIdentitiesTypeOtherId_QNAME, OtherIdType.class, UserIdentitiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "phoneNumber", scope = UserIdentitiesType.class)
    public JAXBElement<String> createUserIdentitiesTypePhoneNumber(String value) {
        return new JAXBElement<String>(_UserIdentitiesTypePhoneNumber_QNAME, String.class, UserIdentitiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "alias", scope = UserIdentitiesType.class)
    public JAXBElement<String> createUserIdentitiesTypeAlias(String value) {
        return new JAXBElement<String>(_UserIdentitiesTypeAlias_QNAME, String.class, UserIdentitiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "email", scope = UserIdentitiesType.class)
    public JAXBElement<String> createUserIdentitiesTypeEmail(String value) {
        return new JAXBElement<String>(_UserIdentitiesTypeEmail_QNAME, String.class, UserIdentitiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "telUri", scope = UserIdentitiesType.class)
    public JAXBElement<String> createUserIdentitiesTypeTelUri(String value) {
        return new JAXBElement<String>(_UserIdentitiesTypeTelUri_QNAME, String.class, UserIdentitiesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "namePrefix", scope = UserPersonalInfoType.class)
    public JAXBElement<String> createUserPersonalInfoTypeNamePrefix(String value) {
        return new JAXBElement<String>(_UserPersonalInfoTypeNamePrefix_QNAME, String.class, UserPersonalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "displayName", scope = UserPersonalInfoType.class)
    public JAXBElement<String> createUserPersonalInfoTypeDisplayName(String value) {
        return new JAXBElement<String>(_UserPersonalInfoTypeDisplayName_QNAME, String.class, UserPersonalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "lastUpdated", scope = UserPersonalInfoType.class)
    public JAXBElement<XMLGregorianCalendar> createUserPersonalInfoTypeLastUpdated(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_UserPersonalInfoTypeLastUpdated_QNAME, XMLGregorianCalendar.class, UserPersonalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "gender", scope = UserPersonalInfoType.class)
    public JAXBElement<GenderType> createUserPersonalInfoTypeGender(GenderType value) {
        return new JAXBElement<GenderType>(_UserPersonalInfoTypeGender_QNAME, GenderType.class, UserPersonalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "address", scope = UserPersonalInfoType.class)
    public JAXBElement<AddressType> createUserPersonalInfoTypeAddress(AddressType value) {
        return new JAXBElement<AddressType>(_UserPersonalInfoTypeAddress_QNAME, AddressType.class, UserPersonalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "nameSufix", scope = UserPersonalInfoType.class)
    public JAXBElement<String> createUserPersonalInfoTypeNameSufix(String value) {
        return new JAXBElement<String>(_UserPersonalInfoTypeNameSufix_QNAME, String.class, UserPersonalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "name", scope = UserPersonalInfoType.class)
    public JAXBElement<NameType> createUserPersonalInfoTypeName(NameType value) {
        return new JAXBElement<NameType>(_UserPersonalInfoTypeName_QNAME, NameType.class, UserPersonalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "birthday", scope = UserPersonalInfoType.class)
    public JAXBElement<XMLGregorianCalendar> createUserPersonalInfoTypeBirthday(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_UserPersonalInfoTypeBirthday_QNAME, XMLGregorianCalendar.class, UserPersonalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "parentalControl", scope = UserProfileType.class)
    public JAXBElement<String> createUserProfileTypeParentalControl(String value) {
        return new JAXBElement<String>(_UserProfileTypeParentalControl_QNAME, String.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "userType", scope = UserProfileType.class)
    public JAXBElement<String> createUserProfileTypeUserType(String value) {
        return new JAXBElement<String>(_UserProfileTypeUserType_QNAME, String.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "lastUpdated", scope = UserProfileType.class)
    public JAXBElement<XMLGregorianCalendar> createUserProfileTypeLastUpdated(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_UserPersonalInfoTypeLastUpdated_QNAME, XMLGregorianCalendar.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "diversionMsisdn", scope = UserProfileType.class)
    public JAXBElement<String> createUserProfileTypeDiversionMsisdn(String value) {
        return new JAXBElement<String>(_UserProfileTypeDiversionMsisdn_QNAME, String.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "operatorId", scope = UserProfileType.class)
    public JAXBElement<String> createUserProfileTypeOperatorId(String value) {
        return new JAXBElement<String>(_UserProfileTypeOperatorId_QNAME, String.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "segment", scope = UserProfileType.class)
    public JAXBElement<String> createUserProfileTypeSegment(String value) {
        return new JAXBElement<String>(_UserProfileTypeSegment_QNAME, String.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "enterpriseName", scope = UserProfileType.class)
    public JAXBElement<String> createUserProfileTypeEnterpriseName(String value) {
        return new JAXBElement<String>(_UserProfileTypeEnterpriseName_QNAME, String.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "restMens", scope = UserProfileType.class)
    public JAXBElement<String> createUserProfileTypeRestMens(String value) {
        return new JAXBElement<String>(_UserProfileTypeRestMens_QNAME, String.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "roaming", scope = UserProfileType.class)
    public JAXBElement<FlagType> createUserProfileTypeRoaming(FlagType value) {
        return new JAXBElement<FlagType>(_UserAccessInfoTypeRoaming_QNAME, FlagType.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MmsStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "mmsStatus", scope = UserProfileType.class)
    public JAXBElement<MmsStatusType> createUserProfileTypeMmsStatus(MmsStatusType value) {
        return new JAXBElement<MmsStatusType>(_UserProfileTypeMmsStatus_QNAME, MmsStatusType.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "ocb", scope = UserProfileType.class)
    public JAXBElement<String> createUserProfileTypeOcb(String value) {
        return new JAXBElement<String>(_UserProfileTypeOcb_QNAME, String.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "subsegment", scope = UserProfileType.class)
    public JAXBElement<String> createUserProfileTypeSubsegment(String value) {
        return new JAXBElement<String>(_UserProfileTypeSubsegment_QNAME, String.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "imsi", scope = UserProfileType.class)
    public JAXBElement<String> createUserProfileTypeImsi(String value) {
        return new JAXBElement<String>(_UserProfileTypeImsi_QNAME, String.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "language", scope = UserProfileType.class)
    public JAXBElement<String> createUserProfileTypeLanguage(String value) {
        return new JAXBElement<String>(_UserProfileTypeLanguage_QNAME, String.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "icc", scope = UserProfileType.class)
    public JAXBElement<String> createUserProfileTypeIcc(String value) {
        return new JAXBElement<String>(_UserProfileTypeIcc_QNAME, String.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "icb", scope = UserProfileType.class)
    public JAXBElement<String> createUserProfileTypeIcb(String value) {
        return new JAXBElement<String>(_UserProfileTypeIcb_QNAME, String.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "simType", scope = UserProfileType.class)
    public JAXBElement<String> createUserProfileTypeSimType(String value) {
        return new JAXBElement<String>(_UserProfileTypeSimType_QNAME, String.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "creditControl", scope = UserProfileType.class)
    public JAXBElement<FlagType> createUserProfileTypeCreditControl(FlagType value) {
        return new JAXBElement<FlagType>(_UserProfileTypeCreditControl_QNAME, FlagType.class, UserProfileType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "screenResolution", scope = UserTerminalInfoType.class)
    public JAXBElement<String> createUserTerminalInfoTypeScreenResolution(String value) {
        return new JAXBElement<String>(_UserTerminalInfoTypeScreenResolution_QNAME, String.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "version", scope = UserTerminalInfoType.class)
    public JAXBElement<String> createUserTerminalInfoTypeVersion(String value) {
        return new JAXBElement<String>(_UserTerminalInfoTypeVersion_QNAME, String.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "ems", scope = UserTerminalInfoType.class)
    public JAXBElement<FlagType> createUserTerminalInfoTypeEms(FlagType value) {
        return new JAXBElement<FlagType>(_UserTerminalInfoTypeEms_QNAME, FlagType.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "emsMaxNumber", scope = UserTerminalInfoType.class)
    public JAXBElement<String> createUserTerminalInfoTypeEmsMaxNumber(String value) {
        return new JAXBElement<String>(_UserTerminalInfoTypeEmsMaxNumber_QNAME, String.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "mms", scope = UserTerminalInfoType.class)
    public JAXBElement<FlagType> createUserTerminalInfoTypeMms(FlagType value) {
        return new JAXBElement<FlagType>(_UserTerminalInfoTypeMms_QNAME, FlagType.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "lastUpdated", scope = UserTerminalInfoType.class)
    public JAXBElement<XMLGregorianCalendar> createUserTerminalInfoTypeLastUpdated(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_UserPersonalInfoTypeLastUpdated_QNAME, XMLGregorianCalendar.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "adc_OTA", scope = UserTerminalInfoType.class)
    public JAXBElement<FlagType> createUserTerminalInfoTypeAdcOTA(FlagType value) {
        return new JAXBElement<FlagType>(_UserTerminalInfoTypeAdcOTA_QNAME, FlagType.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "syncMlVersion", scope = UserTerminalInfoType.class)
    public JAXBElement<String> createUserTerminalInfoTypeSyncMlVersion(String value) {
        return new JAXBElement<String>(_UserTerminalInfoTypeSyncMlVersion_QNAME, String.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "wapPush", scope = UserTerminalInfoType.class)
    public JAXBElement<FlagType> createUserTerminalInfoTypeWapPush(FlagType value) {
        return new JAXBElement<FlagType>(_UserTerminalInfoTypeWapPush_QNAME, FlagType.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "status", scope = UserTerminalInfoType.class)
    public JAXBElement<StatusType> createUserTerminalInfoTypeStatus(StatusType value) {
        return new JAXBElement<StatusType>(_UserTerminalInfoTypeStatus_QNAME, StatusType.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "imei", scope = UserTerminalInfoType.class)
    public JAXBElement<String> createUserTerminalInfoTypeImei(String value) {
        return new JAXBElement<String>(_UserTerminalInfoTypeImei_QNAME, String.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "wap", scope = UserTerminalInfoType.class)
    public JAXBElement<FlagType> createUserTerminalInfoTypeWap(FlagType value) {
        return new JAXBElement<FlagType>(_UserTerminalInfoTypeWap_QNAME, FlagType.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "emn", scope = UserTerminalInfoType.class)
    public JAXBElement<FlagType> createUserTerminalInfoTypeEmn(FlagType value) {
        return new JAXBElement<FlagType>(_UserTerminalInfoTypeEmn_QNAME, FlagType.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "model", scope = UserTerminalInfoType.class)
    public JAXBElement<String> createUserTerminalInfoTypeModel(String value) {
        return new JAXBElement<String>(_UserTerminalInfoTypeModel_QNAME, String.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "smartMessaging", scope = UserTerminalInfoType.class)
    public JAXBElement<FlagType> createUserTerminalInfoTypeSmartMessaging(FlagType value) {
        return new JAXBElement<FlagType>(_UserTerminalInfoTypeSmartMessaging_QNAME, FlagType.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "mmsVideo", scope = UserTerminalInfoType.class)
    public JAXBElement<FlagType> createUserTerminalInfoTypeMmsVideo(FlagType value) {
        return new JAXBElement<FlagType>(_UserTerminalInfoTypeMmsVideo_QNAME, FlagType.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "brand", scope = UserTerminalInfoType.class)
    public JAXBElement<String> createUserTerminalInfoTypeBrand(String value) {
        return new JAXBElement<String>(_UserTerminalInfoTypeBrand_QNAME, String.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "videoStreaming", scope = UserTerminalInfoType.class)
    public JAXBElement<FlagType> createUserTerminalInfoTypeVideoStreaming(FlagType value) {
        return new JAXBElement<FlagType>(_UserTerminalInfoTypeVideoStreaming_QNAME, FlagType.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "email", scope = UserTerminalInfoType.class)
    public JAXBElement<FlagType> createUserTerminalInfoTypeEmail(FlagType value) {
        return new JAXBElement<FlagType>(_UserIdentitiesTypeEmail_QNAME, FlagType.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "syncMl", scope = UserTerminalInfoType.class)
    public JAXBElement<FlagType> createUserTerminalInfoTypeSyncMl(FlagType value) {
        return new JAXBElement<FlagType>(_UserTerminalInfoTypeSyncMl_QNAME, FlagType.class, UserTerminalInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", name = "ussdPhase", scope = UserTerminalInfoType.class)
    public JAXBElement<String> createUserTerminalInfoTypeUssdPhase(String value) {
        return new JAXBElement<String>(_UserTerminalInfoTypeUssdPhase_QNAME, String.class, UserTerminalInfoType.class, value);
    }

}
