//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.30 at 03:11:16 PM CEST 
//


package com.telefonica.schemas.unica.rest.directory.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import com.telefonica.schemas.unica.rest.common.v1.ExtensionType;
import com.telefonica.schemas.unica.rest.common.v1.FlagType;
import com.telefonica.schemas.unica.rest.common.v1.IpAddressType;
import org.w3c.dom.Element;


/**
 * <p>Java class for UserAccessInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserAccessInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="connected" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}FlagType" minOccurs="0"/>
 *         &lt;element name="ipAddress" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}IpAddressType" minOccurs="0"/>
 *         &lt;element name="accessType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="connectionTime" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="apn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="roaming" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}FlagType" minOccurs="0"/>
 *         &lt;element name="extension" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}ExtensionType" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserAccessInfoType", propOrder = {
    "connected",
    "ipAddress",
    "accessType",
    "connectionTime",
    "apn",
    "roaming",
    "extension",
    "any"
})
public class UserAccessInfoType {

    @XmlElementRef(name = "connected", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<FlagType> connected;
    @XmlElementRef(name = "ipAddress", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<IpAddressType> ipAddress;
    @XmlElementRef(name = "accessType", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> accessType;
    @XmlElementRef(name = "connectionTime", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<Long> connectionTime;
    @XmlElementRef(name = "apn", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> apn;
    @XmlElementRef(name = "roaming", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<FlagType> roaming;
    protected ExtensionType extension;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the connected property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FlagType }{@code >}
     *     
     */
    public JAXBElement<FlagType> getConnected() {
        return connected;
    }

    /**
     * Sets the value of the connected property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FlagType }{@code >}
     *     
     */
    public void setConnected(JAXBElement<FlagType> value) {
        this.connected = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link IpAddressType }{@code >}
     *     
     */
    public JAXBElement<IpAddressType> getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link IpAddressType }{@code >}
     *     
     */
    public void setIpAddress(JAXBElement<IpAddressType> value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the accessType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAccessType() {
        return accessType;
    }

    /**
     * Sets the value of the accessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAccessType(JAXBElement<String> value) {
        this.accessType = value;
    }

    /**
     * Gets the value of the connectionTime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getConnectionTime() {
        return connectionTime;
    }

    /**
     * Sets the value of the connectionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setConnectionTime(JAXBElement<Long> value) {
        this.connectionTime = value;
    }

    /**
     * Gets the value of the apn property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getApn() {
        return apn;
    }

    /**
     * Sets the value of the apn property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setApn(JAXBElement<String> value) {
        this.apn = value;
    }

    /**
     * Gets the value of the roaming property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FlagType }{@code >}
     *     
     */
    public JAXBElement<FlagType> getRoaming() {
        return roaming;
    }

    /**
     * Sets the value of the roaming property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FlagType }{@code >}
     *     
     */
    public void setRoaming(JAXBElement<FlagType> value) {
        this.roaming = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setExtension(ExtensionType value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param any
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(List<Object> any) {
        this.any = any;
    }

}
