//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.30 at 03:11:16 PM CEST 
//


package com.telefonica.schemas.unica.rest.directory.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.telefonica.schemas.unica.rest.common.v1.ExtensionType;
import com.telefonica.schemas.unica.rest.common.v1.FlagType;
import org.w3c.dom.Element;


/**
 * <p>Java class for UserProfileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserProfileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userType" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}UserTypeType" minOccurs="0"/>
 *         &lt;element name="imsi" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}ImsiType" minOccurs="0"/>
 *         &lt;element name="icb" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}IcbType" minOccurs="0"/>
 *         &lt;element name="ocb" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}OcbType" minOccurs="0"/>
 *         &lt;element name="language" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}LanguageType" minOccurs="0"/>
 *         &lt;element name="simType" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}SimTypeType" minOccurs="0"/>
 *         &lt;element name="parentalControl" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}ParentalControlType" minOccurs="0"/>
 *         &lt;element name="creditControl" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}FlagType" minOccurs="0"/>
 *         &lt;element name="diversionMsisdn" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}E164Type" minOccurs="0"/>
 *         &lt;element name="enterpriseName" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}EnterpriseNameType" minOccurs="0"/>
 *         &lt;element name="roaming" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}FlagType" minOccurs="0"/>
 *         &lt;element name="operatorId" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}OperatorIdType" minOccurs="0"/>
 *         &lt;element name="mmsStatus" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}MmsStatusType" minOccurs="0"/>
 *         &lt;element name="segment" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}SegmentType" minOccurs="0"/>
 *         &lt;element name="subsegment" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}SubsegmentType" minOccurs="0"/>
 *         &lt;element name="subscribedService" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}SubscribedServiceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="lastUpdated" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}TimestampType" minOccurs="0"/>
 *         &lt;element name="extension" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}ExtensionType" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="icc" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}IccType" minOccurs="0"/>
 *         &lt;element name="restMens" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}RestMensType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserProfileType", propOrder = {
    "userType",
    "imsi",
    "icb",
    "ocb",
    "language",
    "simType",
    "parentalControl",
    "creditControl",
    "diversionMsisdn",
    "enterpriseName",
    "roaming",
    "operatorId",
    "mmsStatus",
    "segment",
    "subsegment",
    "subscribedService",
    "lastUpdated",
    "extension",
    "any",
    "icc",
    "restMens"
})
public class UserProfileType {

    @XmlElementRef(name = "userType", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> userType;
    @XmlElementRef(name = "imsi", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> imsi;
    @XmlElementRef(name = "icb", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> icb;
    @XmlElementRef(name = "ocb", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> ocb;
    @XmlElementRef(name = "language", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> language;
    @XmlElementRef(name = "simType", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> simType;
    @XmlElementRef(name = "parentalControl", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> parentalControl;
    @XmlElementRef(name = "creditControl", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<FlagType> creditControl;
    @XmlElementRef(name = "diversionMsisdn", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> diversionMsisdn;
    @XmlElementRef(name = "enterpriseName", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> enterpriseName;
    @XmlElementRef(name = "roaming", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<FlagType> roaming;
    @XmlElementRef(name = "operatorId", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> operatorId;
    @XmlElementRef(name = "mmsStatus", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<MmsStatusType> mmsStatus;
    @XmlElementRef(name = "segment", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> segment;
    @XmlElementRef(name = "subsegment", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> subsegment;
    @XmlElement(nillable = true)
    protected List<SubscribedServiceType> subscribedService;
    @XmlElementRef(name = "lastUpdated", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> lastUpdated;
    protected ExtensionType extension;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlElementRef(name = "icc", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> icc;
    @XmlElementRef(name = "restMens", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> restMens;

    /**
     * Gets the value of the userType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUserType() {
        return userType;
    }

    /**
     * Sets the value of the userType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUserType(JAXBElement<String> value) {
        this.userType = value;
    }

    /**
     * Gets the value of the imsi property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getImsi() {
        return imsi;
    }

    /**
     * Sets the value of the imsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setImsi(JAXBElement<String> value) {
        this.imsi = value;
    }

    /**
     * Gets the value of the icb property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIcb() {
        return icb;
    }

    /**
     * Sets the value of the icb property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIcb(JAXBElement<String> value) {
        this.icb = value;
    }

    /**
     * Gets the value of the ocb property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOcb() {
        return ocb;
    }

    /**
     * Sets the value of the ocb property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOcb(JAXBElement<String> value) {
        this.ocb = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLanguage(JAXBElement<String> value) {
        this.language = value;
    }

    /**
     * Gets the value of the simType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSimType() {
        return simType;
    }

    /**
     * Sets the value of the simType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSimType(JAXBElement<String> value) {
        this.simType = value;
    }

    /**
     * Gets the value of the parentalControl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getParentalControl() {
        return parentalControl;
    }

    /**
     * Sets the value of the parentalControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setParentalControl(JAXBElement<String> value) {
        this.parentalControl = value;
    }

    /**
     * Gets the value of the creditControl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FlagType }{@code >}
     *     
     */
    public JAXBElement<FlagType> getCreditControl() {
        return creditControl;
    }

    /**
     * Sets the value of the creditControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FlagType }{@code >}
     *     
     */
    public void setCreditControl(JAXBElement<FlagType> value) {
        this.creditControl = value;
    }

    /**
     * Gets the value of the diversionMsisdn property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDiversionMsisdn() {
        return diversionMsisdn;
    }

    /**
     * Sets the value of the diversionMsisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDiversionMsisdn(JAXBElement<String> value) {
        this.diversionMsisdn = value;
    }

    /**
     * Gets the value of the enterpriseName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * Sets the value of the enterpriseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setEnterpriseName(JAXBElement<String> value) {
        this.enterpriseName = value;
    }

    /**
     * Gets the value of the roaming property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FlagType }{@code >}
     *     
     */
    public JAXBElement<FlagType> getRoaming() {
        return roaming;
    }

    /**
     * Sets the value of the roaming property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FlagType }{@code >}
     *     
     */
    public void setRoaming(JAXBElement<FlagType> value) {
        this.roaming = value;
    }

    /**
     * Gets the value of the operatorId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOperatorId() {
        return operatorId;
    }

    /**
     * Sets the value of the operatorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOperatorId(JAXBElement<String> value) {
        this.operatorId = value;
    }

    /**
     * Gets the value of the mmsStatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MmsStatusType }{@code >}
     *     
     */
    public JAXBElement<MmsStatusType> getMmsStatus() {
        return mmsStatus;
    }

    /**
     * Sets the value of the mmsStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MmsStatusType }{@code >}
     *     
     */
    public void setMmsStatus(JAXBElement<MmsStatusType> value) {
        this.mmsStatus = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSegment() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSegment(JAXBElement<String> value) {
        this.segment = value;
    }

    /**
     * Gets the value of the subsegment property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSubsegment() {
        return subsegment;
    }

    /**
     * Sets the value of the subsegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSubsegment(JAXBElement<String> value) {
        this.subsegment = value;
    }

    /**
     * Gets the value of the subscribedService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subscribedService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubscribedService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubscribedServiceType }
     * 
     * 
     */
    public List<SubscribedServiceType> getSubscribedService() {
        if (subscribedService == null) {
            subscribedService = new ArrayList<SubscribedServiceType>();
        }
        return this.subscribedService;
    }

    /**
     * Gets the value of the lastUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Sets the value of the lastUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setLastUpdated(JAXBElement<XMLGregorianCalendar> value) {
        this.lastUpdated = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setExtension(ExtensionType value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the icc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIcc() {
        return icc;
    }

    /**
     * Sets the value of the icc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIcc(JAXBElement<String> value) {
        this.icc = value;
    }

    /**
     * Gets the value of the restMens property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRestMens() {
        return restMens;
    }

    /**
     * Sets the value of the restMens property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRestMens(JAXBElement<String> value) {
        this.restMens = value;
    }

    /**
     * Sets the value of the subscribedService property.
     * 
     * @param subscribedService
     *     allowed object is
     *     {@link SubscribedServiceType }
     *     
     */
    public void setSubscribedService(List<SubscribedServiceType> subscribedService) {
        this.subscribedService = subscribedService;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param any
     *     allowed object is
     *     {@link Element }
     *     {@link Object }
     *     
     */
    public void setAny(List<Object> any) {
        this.any = any;
    }

}
