//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.30 at 03:11:16 PM CEST 
//


package com.telefonica.schemas.unica.rest.directory.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userIdentities" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}UserIdentitiesType" minOccurs="0"/>
 *         &lt;element name="userPersonalInfo" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}UserPersonalInfoType" minOccurs="0"/>
 *         &lt;element name="userProfile" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}UserProfileType" minOccurs="0"/>
 *         &lt;element name="userAccessInfo" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}UserAccessInfoType" minOccurs="0"/>
 *         &lt;element name="userTerminalInfo" type="{http://www.telefonica.com/schemas/UNICA/REST/directory/v1/}UserTerminalInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserInfoType", propOrder = {
    "userIdentities",
    "userPersonalInfo",
    "userProfile",
    "userAccessInfo",
    "userTerminalInfo"
})
public class UserInfoType {

    @XmlElementRef(name = "userIdentities", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<UserIdentitiesType> userIdentities;
    @XmlElementRef(name = "userPersonalInfo", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<UserPersonalInfoType> userPersonalInfo;
    @XmlElementRef(name = "userProfile", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<UserProfileType> userProfile;
    @XmlElementRef(name = "userAccessInfo", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<UserAccessInfoType> userAccessInfo;
    @XmlElementRef(name = "userTerminalInfo", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<UserTerminalInfoType> userTerminalInfo;

    /**
     * Gets the value of the userIdentities property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link UserIdentitiesType }{@code >}
     *     
     */
    public JAXBElement<UserIdentitiesType> getUserIdentities() {
        return userIdentities;
    }

    /**
     * Sets the value of the userIdentities property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link UserIdentitiesType }{@code >}
     *     
     */
    public void setUserIdentities(JAXBElement<UserIdentitiesType> value) {
        this.userIdentities = value;
    }

    /**
     * Gets the value of the userPersonalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link UserPersonalInfoType }{@code >}
     *     
     */
    public JAXBElement<UserPersonalInfoType> getUserPersonalInfo() {
        return userPersonalInfo;
    }

    /**
     * Sets the value of the userPersonalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link UserPersonalInfoType }{@code >}
     *     
     */
    public void setUserPersonalInfo(JAXBElement<UserPersonalInfoType> value) {
        this.userPersonalInfo = value;
    }

    /**
     * Gets the value of the userProfile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link UserProfileType }{@code >}
     *     
     */
    public JAXBElement<UserProfileType> getUserProfile() {
        return userProfile;
    }

    /**
     * Sets the value of the userProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link UserProfileType }{@code >}
     *     
     */
    public void setUserProfile(JAXBElement<UserProfileType> value) {
        this.userProfile = value;
    }

    /**
     * Gets the value of the userAccessInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link UserAccessInfoType }{@code >}
     *     
     */
    public JAXBElement<UserAccessInfoType> getUserAccessInfo() {
        return userAccessInfo;
    }

    /**
     * Sets the value of the userAccessInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link UserAccessInfoType }{@code >}
     *     
     */
    public void setUserAccessInfo(JAXBElement<UserAccessInfoType> value) {
        this.userAccessInfo = value;
    }

    /**
     * Gets the value of the userTerminalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link UserTerminalInfoType }{@code >}
     *     
     */
    public JAXBElement<UserTerminalInfoType> getUserTerminalInfo() {
        return userTerminalInfo;
    }

    /**
     * Sets the value of the userTerminalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link UserTerminalInfoType }{@code >}
     *     
     */
    public void setUserTerminalInfo(JAXBElement<UserTerminalInfoType> value) {
        this.userTerminalInfo = value;
    }

}
