//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.30 at 03:11:16 PM CEST 
//


package com.telefonica.schemas.unica.rest.directory.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import com.telefonica.schemas.unica.rest.common.v1.IpAddressType;
import com.telefonica.schemas.unica.rest.common.v1.OtherIdType;


/**
 * <p>Java class for UserIdentitiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserIdentitiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="phoneNumber" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}E164Type" minOccurs="0"/>
 *         &lt;element name="telUri" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}TelUriType" minOccurs="0"/>
 *         &lt;element name="sipUri" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}SipUriType" minOccurs="0"/>
 *         &lt;element name="email" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}EmailAddressType" minOccurs="0"/>
 *         &lt;element name="ipAddress" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}IpAddressType" minOccurs="0"/>
 *         &lt;element name="alias" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}AliasType" minOccurs="0"/>
 *         &lt;element name="otherId" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}OtherIdType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserIdentitiesType", propOrder = {
    "phoneNumber",
    "telUri",
    "sipUri",
    "email",
    "ipAddress",
    "alias",
    "otherId"
})
public class UserIdentitiesType {

    @XmlElementRef(name = "phoneNumber", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> phoneNumber;
    @XmlElementRef(name = "telUri", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> telUri;
    @XmlElementRef(name = "sipUri", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> sipUri;
    @XmlElementRef(name = "email", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> email;
    @XmlElementRef(name = "ipAddress", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<IpAddressType> ipAddress;
    @XmlElementRef(name = "alias", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<String> alias;
    @XmlElementRef(name = "otherId", namespace = "http://www.telefonica.com/schemas/UNICA/REST/directory/v1/", type = JAXBElement.class)
    protected JAXBElement<OtherIdType> otherId;

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPhoneNumber(JAXBElement<String> value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the telUri property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTelUri() {
        return telUri;
    }

    /**
     * Sets the value of the telUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTelUri(JAXBElement<String> value) {
        this.telUri = value;
    }

    /**
     * Gets the value of the sipUri property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSipUri() {
        return sipUri;
    }

    /**
     * Sets the value of the sipUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSipUri(JAXBElement<String> value) {
        this.sipUri = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setEmail(JAXBElement<String> value) {
        this.email = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link IpAddressType }{@code >}
     *     
     */
    public JAXBElement<IpAddressType> getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link IpAddressType }{@code >}
     *     
     */
    public void setIpAddress(JAXBElement<IpAddressType> value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAlias(JAXBElement<String> value) {
        this.alias = value;
    }

    /**
     * Gets the value of the otherId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link OtherIdType }{@code >}
     *     
     */
    public JAXBElement<OtherIdType> getOtherId() {
        return otherId;
    }

    /**
     * Sets the value of the otherId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link OtherIdType }{@code >}
     *     
     */
    public void setOtherId(JAXBElement<OtherIdType> value) {
        this.otherId = value;
    }

}
