//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.30 at 03:11:16 PM CEST 
//


package com.telefonica.schemas.unica.rest.common.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.telefonica.schemas.unica.rest.common.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ServerException_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/common/v1", "ServerException");
    private final static QName _ClientException_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/common/v1", "ClientException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.telefonica.schemas.unica.rest.common.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServerExceptionType }
     * 
     */
    public ServerExceptionType createServerExceptionType() {
        return new ServerExceptionType();
    }

    /**
     * Create an instance of {@link ClientExceptionType }
     * 
     */
    public ClientExceptionType createClientExceptionType() {
        return new ClientExceptionType();
    }

    /**
     * Create an instance of {@link UserIdType }
     * 
     */
    public UserIdType createUserIdType() {
        return new UserIdType();
    }

    /**
     * Create an instance of {@link OtherIdType }
     * 
     */
    public OtherIdType createOtherIdType() {
        return new OtherIdType();
    }

    /**
     * Create an instance of {@link SimpleReferenceType }
     * 
     */
    public SimpleReferenceType createSimpleReferenceType() {
        return new SimpleReferenceType();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link IpAddressType }
     * 
     */
    public IpAddressType createIpAddressType() {
        return new IpAddressType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServerExceptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/common/v1", name = "ServerException")
    public JAXBElement<ServerExceptionType> createServerException(ServerExceptionType value) {
        return new JAXBElement<ServerExceptionType>(_ServerException_QNAME, ServerExceptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientExceptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/common/v1", name = "ClientException")
    public JAXBElement<ClientExceptionType> createClientException(ClientExceptionType value) {
        return new JAXBElement<ClientExceptionType>(_ClientException_QNAME, ClientExceptionType.class, null, value);
    }

}
